### ISSUE TITLE
作业同步报错

### ISSUE THREAD

**Issue by xuetong520** [PKUHPC/scow-slurm-adapter#10]
{"level":"info","msg":"Received request GetJobs: fields:\"job_id\" fields:\"name\" fields:\"user\" fields:\"account\" fields:\"cpus_alloc\" fields:\"gpus_alloc\" fields:\"mem_alloc_mb\" fie              lds:\"mem_req_mb\" fields:\"partition\" fields:\"qos\" fields:\"elapsed_seconds\" fields:\"node_list\" fields:\"nodes_req\" fields:\"nodes_alloc\" fields:\"time_limit_minutes\" fields:\"sub              mit_time\" fields:\"start_time\" fields:\"end_time\" filter:{end_time:{start_time:{} end_time:{seconds:1694659142 nanos:534000000}}}","time":"2023-09-14T10:39:02+08:00"}
2023/09/14 10:39:03 ERROR: [core] [Server #1] grpc: server failed to encode response: rpc error: code = Internal desc = grpc: error while marshaling: string field contains invalid UTF-8

**Comment by yangjie727** [comment]
您数据库的编码在配置文件里面设置一下
