### ISSUE TITLE
adapter跨平台获取系统底层信息会有问题

### ISSUE THREAD

**Issue by kyrieqing7** [PKUHPC/scow-slurm-adapter#12]
adaptor涉及到底层系统调用的时候建议使用go标准库或者直接用cmd命令行执行，因为os包的这个方法如果交叉编译之后根据username获取系统uid会有问题 
macos 交叉编译成linux的可执行二进制文件之后用os这个方法获取uid会有问题
![4121702287911_ pic](https://github.com/PKUHPC/scow-slurm-adapter/assets/148175791/ca9fece7-3e05-4b00-a9df-320ab89b7816)

**Comment by Miracle575** [comment]
该问题暂时不考虑修改。适配器的编译建议在目标平台上进行原生编译
