### ISSUE TITLE
scow 不应该限制用户名或者账号名中包含大写字母

### ISSUE THREAD

**Issue by link89** [PKUHPC/scow-slurm-adapter#24]
无论是 在 linux 还是在 slurm 中，用户名、账号名包含大小写、连字符都是合法的。SCOW 没有必要对其进行限制。这一限制导致部分用户的操作无法正常执行。

https://github.com/PKUHPC/scow-slurm-adapter/blob/master/utils/utils.go#L340-L350

**Comment by tongchong** [comment]
slurm中，账户名、用户名是不能包含大写，可以创建用户、账户成功，但无法提交作业及执行部分命令，所以我们对此做了限制

**Comment by link89** [comment]
@tongchong 那是否可以修改以允许连字符？

**Comment by tongchong** [comment]
在大多数 Linux 系统中，用户名应该遵循 POSIX 规范，即只能包含小写字母（a-z）、数字（0-9）、下划线（_），并且长度限制通常为 32 个字符以内。  最初的时候，我们也是没有限制的，后来与产品沟通后，觉得应该对此进行限制以减少后续维护系统出现的问题。所以如果您要解除限制，可能需要您自己修改一下适配器中的代码。scow的正则是可以配置的，无需修改代码

**Comment by link89** [comment]
我们现在使用自己编译的 adapter 是可以规避这个问题，但为了减少未来的维护成本，还是希望能和社区一起解决。

POSIX 的规范中是允许大写和连字符的，或许就目前来看，添加连字符应该是最好的妥协：既不会触发slurm用户默认不区分大小写的问题，同时可以兼容带有 - 的linux 用户。

Reference: https://systemd.io/USER_NAMES/

> On POSIX the set of [valid user names](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_437) is defined as [lower and upper case ASCII letters, digits, period, underscore, and hyphen](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_282), with the restriction that hyphen is not allowed as first character of the user name. Interestingly no size limit is declared, i.e. in neither direction, meaning that strictly speaking, according to POSIX, both the empty string is a valid user name as well as a string of gigabytes in length.

**Comment by tongchong** [comment]
感谢回复。您可以提交一个pr，我们会讨论并权衡风险，来决定是否合并此pr

**Comment by link89** [comment]
好，我修改了这个 PR: https://github.com/PKUHPC/scow-slurm-adapter/pull/25  目前就只增加了对 - 的允许。
