### ISSUE TITLE
[bug] 添加用户时分区名不区分大小写导致用户无法提交作业

### ISSUE THREAD

**Issue by lijiext** [PKUHPC/scow-slurm-adapter#27]
## 问题描述
当SLURM中存在两个分区，例如TEST和test时，SCOW创建的用户的过程只会成功一部分
![image](https://github.com/user-attachments/assets/8757fb58-086c-44a9-88c9-e2dffeb8e2ef)

如果SLURM中还存在其他分区，那么这些分区的添加将会失败，导致用户无法提交作业
![image](https://github.com/user-attachments/assets/4118480b-0765-4dea-82d1-a1bbc58ae3de)

适配器源代码：
https://github.com/PKUHPC/scow-slurm-adapter/blob/954f678208c3e42301f57690e41a22d33332eb13/services/user/user.go#L114

**Comment by Miracle575** [comment]
问题反馈已收到，后续我们会跟进处理

**Comment by vanstriker** [comment]
不建议在slurm中使用仅有大小写区别的分区名，适配器暂时没有针对该需求更新的计划
