### ISSUE TITLE
GLIBC打包版本过高

### ISSUE THREAD

**Issue by xuetong520** [PKUHPC/scow-slurm-adapter#7]
glibc打包为2.33和2.34版本过高导致默认的centos7 glibc2.17无法使用

**Comment by xuetong520** [comment]
找一台glibc低版本重新打包

**Comment by yangjie727** [comment]
> 找一台glibc低版本重新打包

release版本是github ci打包生成的，如果直接部署包glibc版本过高的话，可以自己找台机器重新编译打包。

**Comment by vanstriker** [comment]
无更新反馈，关闭issue
