### ISSUE TITLE
当有job任务时，切换管理系统程序报错退出

### ISSUE THREAD

**Issue by xuetong520** [PKUHPC/scow-slurm-adapter#8]
{"level":"info","msg":"Received request GetJobs: fields:"job_id" fields:"partition" fields:"name" fields:"user" fields:"state" fields:"elapsed_seconds" fields:"nodes_alloc" fields:"node_list" fields:"reason" fields:"account" fields:"cpus_alloc" fields:"gpus_alloc" fields:"qos" fields:"submit_time" fields:"time_limit_minutes" fields:"working_directory" filter:{users:"tong.xue" states:"RUNNING" states:"PENDING"}","time":"2023-08-10T14:11:42+08:00"}
panic: runtime error: index out of range [1] with length 1

goroutine 11 [running]:
main.(*serverJob).GetJobs(0xe3bf60?, {0xab00c0?, 0xc0001b5830?}, 0xc000094b40)
/root/scow-slurm-adapter/main.go:1900 +0xa14c
scow-slurm-adapter/gen/go._JobService_GetJobs_Handler({0x96ce80?, 0xe3bf60}, {0xab00c0, 0xc0001b5830}, 0xc0001db420, 0x0)
/root/scow-slurm-adapter/gen/go/job_grpc.pb.go:225 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001ae1e0, {0xab2f58, 0xc0000f9040}, 0xc0000d3d40, 0xc0001b52f0, 0xdfef60, 0x0)
/usr/local/gopath/pkg/mod/google.golang.org/grpc@v1.55.0/server.go:1337 +0xdf0
google.golang.org/grpc.(*Server).handleStream(0xc0001ae1e0, {0xab2f58, 0xc0000f9040}, 0xc0000d3d40, 0x0)
/usr/local/gopath/pkg/mod/google.golang.org/grpc@v1.55.0/server.go:1714 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.1()
/usr/local/gopath/pkg/mod/google.golang.org/grpc@v1.55.0/server.go:959 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
/usr/local/gopath/pkg/mod/google.golang.org/grpc@v1.55.0/server.go:957 +0x18c

**Comment by xuetong520** [comment]
存在GPU的场景中会报错退出，CPU环境正常

**Comment by xuetong520** [comment]
存在多机多卡GPU的场景中会报错退出，单机单卡正常

**Comment by xuetong520** [comment]
1897                         var singerJobTimeSubmit *timestamppb.Timestamp
1898                         if len(v) != 0 {
1899                                 singerJobInfo := strings.Split(v, " ")
#添加以下代码临时解决
1900                                 if len(singerJobInfo)<17{
1901                                         continue
1902                                 }
#
1903                                 singerJobAccount := singerJobInfo[1]
1904                                 singerJobUserName := singerJobInfo[13]
1905                                 singerJobJobId, _ := strconv.Atoi(singerJobInfo[2])
1906                                 singerJobState := singerJobInfo[12]
1907                                 singerJobJobPartition := singerJobInfo[9]
1908                                 singerJobJobName := singerJobInfo[5]
1909                                 singerJobQos := singerJobInfo[10]
1910                                 singerJobWorkingDirectory := singerJobInfo[15]
1911                                 // singerJobtimeLimitMinutes, _ := strconv.Atoi(singerJobInfo[6])
1912                                 singerJobtimeLimitMinutes := utils.GetTimeLimit(singerJobInfo[6])

**Comment by yangjie727** [comment]
> 存在多机多卡GPU的场景中会报错退出，单机单卡正常

这个是个bug，接下来会安排修复。

**Comment by vanstriker** [comment]
无更新反馈，关闭issue
